# Generated by Django 6.0.5 on 2026-05-17 11:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama lengkap')),
                ('identity_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor identitas')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Nomor telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor polisi')),
                ('brand', models.CharField(max_length=80, verbose_name='Merek')),
                ('model', models.CharField(max_length=80, verbose_name='Model')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Warna')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Otomatis')], max_length=20, verbose_name='Transmisi')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Bensin'), ('diesel', 'Solar'), ('electric', 'Listrik'), ('hybrid', 'Hybrid')], max_length=20, verbose_name='Jenis bahan bakar')),
                ('seat_count', models.PositiveSmallIntegerField(default=4, verbose_name='Jumlah kursi')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif harian (Rp)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Uang jaminan (Rp)')),
                ('odometer', models.PositiveIntegerField(verbose_name='Odometer')),
                ('status', models.CharField(choices=[('available', 'Tersedia'), ('rented', 'Disewa'), ('maintenance', 'Perawatan'), ('inactive', 'Tidak aktif')], default='available', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Kendaraan',
                'verbose_name_plural': 'Kendaraan',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori kendaraan',
                'verbose_name_plural': 'Kategori kendaraan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='Nomor invoice')),
                ('start_at', models.DateTimeField(verbose_name='Mulai sewa')),
                ('expected_return_at', models.DateTimeField(verbose_name='Rencana kembali')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu kembali')),
                ('start_odometer', models.PositiveIntegerField(verbose_name='Odometer awal')),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer akhir')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif harian (Rp)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diskon (Rp)')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Biaya tambahan (Rp)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Uang jaminan (Rp)')),
                ('status', models.CharField(choices=[('draft', 'Draf'), ('active', 'Aktif'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.customer', verbose_name='Pelanggan')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.vehicle', verbose_name='Kendaraan')),
            ],
            options={
                'verbose_name': 'Transaksi rental',
                'verbose_name_plural': 'Transaksi rental',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal pembayaran')),
                ('method', models.CharField(choices=[('cash', 'Tunai'), ('bank_transfer', 'Transfer bank'), ('debit_card', 'Kartu debit'), ('credit_card', 'Kartu kredit'), ('qris', 'QRIS')], max_length=20, verbose_name='Metode pembayaran')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah pembayaran (Rp)')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental', verbose_name='Transaksi rental')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='rentals.vehiclecategory', verbose_name='Kategori kendaraan'),
        ),
    ]
