# Generated by Django 6.0.5 on 2026-05-24 06:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_maintenance_categories(apps, schema_editor):
    maintenance_category = apps.get_model('rentals', 'MaintenanceCategory')
    defaults = [
        ('Penggantian oli', 'oil', 'Penggantian oli mesin, oli transmisi, atau oli gardan.'),
        ('Sparepart mesin', 'engine', 'Penggantian atau perbaikan sparepart area mesin.'),
        ('Kaki-kaki', 'suspension', 'Service shockbreaker, tie rod, ball joint, bearing, dan komponen kaki-kaki.'),
        ('Service accu', 'battery', 'Pemeriksaan, charge, atau penggantian accu.'),
        ('Lainnya', 'other', 'Kategori custom untuk pekerjaan maintenance lain.'),
    ]
    for name, category_type, description in defaults:
        maintenance_category.objects.get_or_create(
            name=name,
            defaults={
                'category_type': category_type,
                'description': description,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama kategori maintenance')),
                ('category_type', models.CharField(choices=[('oil', 'Penggantian oli'), ('engine', 'Sparepart mesin'), ('suspension', 'Kaki-kaki'), ('battery', 'Service accu'), ('other', 'Lainnya')], default='other', max_length=20, verbose_name='Jenis maintenance')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori maintenance',
                'verbose_name_plural': 'Kategori maintenance',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nama bengkel/vendor')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Kontak person')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Nomor telepon')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Vendor bengkel',
                'verbose_name_plural': 'Vendor bengkel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('maintenance_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal maintenance')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer')),
                ('issue_description', models.TextField(verbose_name='Masalah / pekerjaan')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Sparepart yang diganti')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Biaya pengeluaran (Rp)')),
                ('status', models.CharField(choices=[('planned', 'Direncanakan'), ('in_progress', 'Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='completed', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rentals.maintenancecategory', verbose_name='Kategori maintenance')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rentals.vehicle', verbose_name='Kendaraan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rentals.maintenancevendor', verbose_name='Vendor bengkel')),
            ],
            options={
                'verbose_name': 'Maintenance kendaraan',
                'verbose_name_plural': 'Maintenance kendaraan',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.RunPython(create_default_maintenance_categories, migrations.RunPython.noop),
    ]
