# Generated by Django 6.0.5 on 2026-05-25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def create_default_expense_types(apps, schema_editor):
    expense_type = apps.get_model('rentals', 'ExpenseType')
    defaults = [
        ('Pajak kendaraan', 'Pajak tahunan, STNK, atau biaya resmi kendaraan.'),
        ('Pembelian aksesoris mobil', 'Aksesoris, perlengkapan, atau upgrade unit rental.'),
        ('Alat kerja kantor', 'Peralatan dan perlengkapan operasional kantor.'),
        ('Operasional kantor', 'Biaya rutin kantor seperti listrik, internet, atau ATK.'),
        ('Lainnya', 'Jenis biaya usaha lainnya.'),
    ]
    for name, description in defaults:
        expense_type.objects.get_or_create(
            name=name,
            defaults={'description': description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_maintenancecategory_maintenancevendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama jenis biaya')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Jenis biaya',
                'verbose_name_plural': 'Jenis biaya',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal biaya')),
                ('payee', models.CharField(blank=True, max_length=150, verbose_name='Penerima / vendor')),
                ('description', models.TextField(verbose_name='Uraian biaya')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Biaya pengeluaran (Rp)')),
                ('status', models.CharField(choices=[('planned', 'Direncanakan'), ('in_progress', 'Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='completed', max_length=20, verbose_name='Status')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor referensi')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='rentals.expensetype', verbose_name='Jenis biaya')),
            ],
            options={
                'verbose_name': 'Biaya lain',
                'verbose_name_plural': 'Biaya lain',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.RunPython(create_default_expense_types, migrations.RunPython.noop),
    ]
