# Generated by Django 6.0.5 on 2026-06-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_expensetype_otherexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'verbose_name': 'Daftar pelanggan', 'verbose_name_plural': 'Daftar pelanggan'},
        ),
        migrations.AlterModelOptions(
            name='maintenancevendor',
            options={'ordering': ['name'], 'verbose_name': 'Daftar bengkel', 'verbose_name_plural': 'Daftar bengkel'},
        ),
        migrations.AlterModelOptions(
            name='otherexpense',
            options={'ordering': ['-expense_date'], 'verbose_name': 'Biaya lain-lain', 'verbose_name_plural': 'Biaya lain-lain'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Order payment', 'verbose_name_plural': 'Order payment'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-start_at'], 'verbose_name': 'Order rental', 'verbose_name_plural': 'Order rental'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'verbose_name': 'Daftar kendaraan', 'verbose_name_plural': 'Daftar kendaraan'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental', verbose_name='Order rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.customer', verbose_name='Daftar pelanggan'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.vehicle', verbose_name='Daftar kendaraan'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rentals.vehicle', verbose_name='Daftar Kendaraan'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='rentals.maintenancevendor', verbose_name='Daftar bengkel'),
        ),
    ]
