# Generated by Django 6.0.5 on 2026-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL foto')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
            ],
            options={
                'verbose_name': 'Foto kendaraan',
                'verbose_name_plural': 'Foto kendaraan',
                'db_table': 'vehicle_photos',
                'ordering': ['order'],
                'managed': False,
            },
        ),
    ]
