# Generated by Django 6.0.5 on 2026-06-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_vehiclephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expenses', to='rentals.rental', verbose_name='Terkait order rental'),
        ),
    ]
