# Generated by Django 6.0.5 on 2026-06-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_otherexpense_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='additional_fee_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Uraian biaya tambahan'),
        ),
    ]
