# Generated by Django 6.0.5 on 2026-06-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rental_additional_fee_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada')),
                ('menu_key', models.CharField(max_length=100, verbose_name='Menu key')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu favorit',
                'verbose_name_plural': 'Menu favorit',
                'db_table': 'menu_favorites',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'menu_key')},
            },
        ),
    ]
