# Generated by Django 6.0.5 on 2026-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_menufavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nomor invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nomor invoice'),
        ),
    ]
