# Generated by Django 6.0.5 on 2026-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_otherexpense_invoice_number_payment_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Nomor order'),
        ),
    ]
